format = """\
    $time\
    $directory\
    $username\
    $hostname\
    $kubernetes\
    $git_branch\
    $git_state\
    $git_status\
    $package\
    $dotnet\
    $golang\
    $java\
    $nodejs\
    $python\
    $ruby\
    $rust\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $env_var\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $character\
"""

[character]
# theme 1
# success_symbol = "ğŸŸ¢ "
# error_symbol = "ğŸ”´ "
# vicmd_symbol = "âšª "

# theme 2
success_symbol = "â– "
error_symbol = "âœ–ï¸  "
vicmd_symbol = "â• "

# theme 3
# success_symbol = "ğŸ’š "
# error_symbol = "â¤ï¸  "
# vicmd_symbol = "ğŸ¤ "

[directory]
fish_style_pwd_dir_length = 10
style = "67"

[git_branch]
symbol = "ğŸŒ¿ "
style = "28"

[git_status]
style = "28"

[line_break]
disabled = true

[time]
disabled = false
style = "240"
format = "[$time]($style) "

[nodejs]
disabled = true

[cmd_duration]
min_time = 3000
style = "88"
format = "â±ï¸  [$duration]($style) "

[aws]
disabled = true
